version: '3'

services:
  mongo:
    image: mongo:3.6.4-jessie
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - /data/db
